# Ported from Mobile-Harness (https://github.com/techjarves/Mobile-Harness)
# Original: app/src/main/cpp/GenerateLoaderInfo.cmake

# Generate loader-info.c from the prootloader executable
# This extracts the entry point and load address for the PRoot loader

cmake_minimum_required(VERSION 3.22.1)

if(NOT DEFINED READELF)
    message(FATAL_ERROR "READELF not defined")
endif()

if(NOT DEFINED LOADER)
    message(FATAL_ERROR "LOADER not defined")
endif()

if(NOT DEFINED OUTPUT)
    message(FATAL_ERROR "OUTPUT not defined")
endif()

execute_process(
    COMMAND ${READELF} -h ${LOADER}
    OUTPUT_VARIABLE READ_ELF_OUTPUT
    RESULT_VARIABLE READ_ELF_RESULT
    OUTPUT_STRIP_TRAILING_WHITESPACE
)

if(NOT READ_ELF_RESULT EQUAL 0)
    message(FATAL_ERROR "readelf failed: ${READ_ELF_OUTPUT}")
endif()

# Extract entry point address
string(REGEX MATCH "Entry point address:[[:space:]]+(0x[0-9a-fA-F]+)" ENTRY_MATCH ${READ_ELF_OUTPUT})
if(NOT ENTRY_MATCH)
    message(FATAL_ERROR "Could not find entry point in readelf output")
endif()
set(ENTRY_POINT ${CMAKE_MATCH_1})

# Extract program headers for load address
execute_process(
    COMMAND ${READELF} -l ${LOADER}
    OUTPUT_VARIABLE READ_ELF_PHDR_OUTPUT
    RESULT_VARIABLE READ_ELF_PHDR_RESULT
    OUTPUT_STRIP_TRAILING_WHITESPACE
)

if(NOT READ_ELF_PHDR_RESULT EQUAL 0)
    message(FATAL_ERROR "readelf -l failed: ${READ_ELF_PHDR_OUTPUT}")
endif()

# Find the LOAD segment with R E permissions (text segment)
string(REGEX MATCHALL "LOAD[[:space:]]+0x[0-9a-fA-F]+[[:space:]]+0x[0-9a-fA-F]+[[:space:]]+0x[0-9a-fA-F]+[[:space:]]+0x[0-9a-fA-F]+[[:space:]]+0x[0-9a-fA-F]+[[:space:]]+0x[0-9a-fA-F]+[[:space:]]+R E" LOAD_MATCHES ${READ_ELF_PHDR_OUTPUT})
if(NOT LOAD_MATCHES)
    message(FATAL_ERROR "Could not find LOAD segment with R E permissions")
endif()

# Parse the first LOAD segment with R E
foreach(LOAD_LINE ${LOAD_MATCHES})
    string(REGEX MATCH "0x([0-9a-fA-F]+)[[:space:]]+0x([0-9a-fA-F]+)[[:space:]]+0x([0-9a-fA-F]+)[[:space:]]+0x([0-9a-fA-F]+)[[:space:]]+0x([0-9a-fA-F]+)[[:space:]]+0x([0-9a-fA-F]+)" LOAD_PARSE ${LOAD_LINE})
    if(LOAD_PARSE)
        set(LOAD_ADDR ${CMAKE_MATCH_2})
        break()
    endif()
endforeach()

if(NOT LOAD_ADDR)
    message(FATAL_ERROR "Could not parse LOAD segment address")
endif()

# Write the loader-info.c
file(WRITE ${OUTPUT} [=[
/* Generated by GenerateLoaderInfo.cmake - DO NOT EDIT */

#ifndef LOADER_INFO_H
#define LOADER_INFO_H

#define PROOT_LOADER_ENTRY_POINT ${ENTRY_POINT}
#define PROOT_LOADER_LOAD_ADDR ${LOAD_ADDR}

#endif /* LOADER_INFO_H */
]=])

message(STATUS "Generated loader-info.c: entry=${ENTRY_POINT}, load_addr=${LOAD_ADDR}")